DROP TABLE IF EXISTS LOCATIONS_SPAIN;
CREATE TABLE LOCATIONS_SPAIN (
    NAME_LOCATION VARCHAR(255) PRIMARY KEY,
    LAT FLOAT NOT NULL,
    LON FLOAT NOT NULL,
    COMUNIDAD VARCHAR(255) NOT NULL,
    PROVINCIA VARCHAR(255) NOT NULL,
    HABITANTES NUMERIC NOT NULL
);

DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(25) NOT NULL UNIQUE,
    PASSWORD_ENCRYPTED VARCHAR(255) NOT NULL,
    NAME_LOCATION VARCHAR(255) -- REFERENCES LOCATIONS_SPAIN(NAME_LOCATION)
);
